name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug and Release
        run: ./gradlew assembleDebug assembleRelease

      - name: Run unit tests
        run: ./gradlew test

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: audiofocus-apks
          path: app/build/outputs/apk/**/*.apk
